version: '3.8'

services:
  flask_app:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    volumes:
      - ./app:/app
      - flask_dependencies:/app/dependencies
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  flask_dependencies:
  db_data:

